name: Auto Release Cloudflared

on:
  schedule:
    - cron: '0 0 */15 * *'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Get latest cloudflared version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r .tag_name)
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Download and compress binaries
        run: |
          VERSION=${{ steps.get_version.outputs.latest_version }}
          
          # Download AMD64 binary
          curl -L "https://github.com/cloudflare/cloudflared/releases/download/${VERSION}/cloudflared-linux-amd64" -o cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          
          # Download ARM64 binary
          curl -L "https://github.com/cloudflare/cloudflared/releases/download/${VERSION}/cloudflared-linux-arm64" -o cloudflared-linux-arm64
          chmod +x cloudflared-linux-arm64
          
          # Create compressed versions for AMD64
          cp cloudflared-linux-amd64 cloudflared-linux-amd64-2x
          cp cloudflared-linux-amd64 cloudflared-linux-amd64-5x
          cp cloudflared-linux-amd64 cloudflared-linux-amd64-9x
          
          # Create compressed versions for ARM64
          cp cloudflared-linux-arm64 cloudflared-linux-arm64-2x
          cp cloudflared-linux-arm64 cloudflared-linux-arm64-5x
          cp cloudflared-linux-arm64 cloudflared-linux-arm64-9x
          
          # Compress with UPX at different levels
          upx -2 cloudflared-linux-amd64-2x cloudflared-linux-arm64-2x
          upx -5 cloudflared-linux-amd64-5x cloudflared-linux-arm64-5x
          upx -9 cloudflared-linux-amd64-9x cloudflared-linux-arm64-9x
          
          # Generate SHA256 checksums for all files
          echo "# Original binaries:" > SHA256SUMS
          sha256sum cloudflared-linux-amd64 >> SHA256SUMS
          sha256sum cloudflared-linux-arm64 >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (2x):" >> SHA256SUMS
          sha256sum cloudflared-linux-amd64-2x >> SHA256SUMS
          sha256sum cloudflared-linux-arm64-2x >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (5x):" >> SHA256SUMS
          sha256sum cloudflared-linux-amd64-5x >> SHA256SUMS
          sha256sum cloudflared-linux-arm64-5x >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (9x):" >> SHA256SUMS
          sha256sum cloudflared-linux-amd64-9x >> SHA256SUMS
          sha256sum cloudflared-linux-arm64-9x >> SHA256SUMS

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cloudflared
          name: cloudflared
          body: |
            cloudflared ${{ steps.get_version.outputs.latest_version }}
            
            Automated release of cloudflared binaries.
            
            This release includes:
            - Original versions
            - 2x compressed versions (UPX level 2)
            - 5x compressed versions (UPX level 5)
            - 9x compressed versions (UPX level 9)
            
            Choose compression level based on your needs:
            - 2x: Faster compression, moderate size reduction
            - 5x: Balanced compression
            - 9x: Maximum compression, slower decompression
            
            SHA256 checksums are provided in SHA256SUMS file.
          files: |
            cloudflared-linux-amd64
            cloudflared-linux-arm64
            cloudflared-linux-amd64-2x
            cloudflared-linux-arm64-2x
            cloudflared-linux-amd64-5x
            cloudflared-linux-arm64-5x
            cloudflared-linux-amd64-9x
            cloudflared-linux-arm64-9x
            SHA256SUMS
          draft: false
          prerelease: false

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
