name: Auto Release Cloudflared

on:
  schedule:
    - cron: '0 0 */15 * *'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Get latest cloudflared version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r .tag_name)
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Download and compress binaries
        run: |
          VERSION=${{ steps.get_version.outputs.latest_version }}
          
          # Download binaries
          curl -L "https://github.com/cloudflare/cloudflared/releases/download/${VERSION}/cloudflared-linux-amd64" -o cloudflared-linux-amd64
          curl -L "https://github.com/cloudflare/cloudflared/releases/download/${VERSION}/cloudflared-linux-arm64" -o cloudflared-linux-arm64
          chmod +x cloudflared-linux-*
          
          # Record original sizes
          echo "Original file sizes:" > SIZE_INFO
          ls -lh cloudflared-linux-* >> SIZE_INFO
          
          # Create compressed versions
          for ARCH in amd64 arm64; do
            # 2x compression (--best --lzma --no-compress-icons)
            cp cloudflared-linux-${ARCH} cloudflared-linux-${ARCH}-2x
            upx --best --lzma --no-compress-icons cloudflared-linux-${ARCH}-2x
            
            # 5x compression (--brute --lzma --no-compress-icons)
            cp cloudflared-linux-${ARCH} cloudflared-linux-${ARCH}-5x
            upx --brute --lzma --no-compress-icons cloudflared-linux-${ARCH}-5x
            
            # 9x compression (--ultra-brute --lzma --all-methods --no-compress-icons)
            cp cloudflared-linux-${ARCH} cloudflared-linux-${ARCH}-9x
            upx --ultra-brute --lzma --all-methods --no-compress-icons cloudflared-linux-${ARCH}-9x
          done
          
          # Record compressed sizes
          echo -e "\nCompressed file sizes:" >> SIZE_INFO
          ls -lh cloudflared-linux-*-[259]x >> SIZE_INFO
          
          # Generate SHA256 checksums
          echo "# Original binaries:" > SHA256SUMS
          sha256sum cloudflared-linux-amd64 >> SHA256SUMS
          sha256sum cloudflared-linux-arm64 >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (2x):" >> SHA256SUMS
          sha256sum cloudflared-linux-*-2x >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (5x):" >> SHA256SUMS
          sha256sum cloudflared-linux-*-5x >> SHA256SUMS
          echo -e "\n# UPX compressed binaries (9x):" >> SHA256SUMS
          sha256sum cloudflared-linux-*-9x >> SHA256SUMS
          
          # Verify all files are executable and not corrupted
          echo -e "\nVerifying compressed files:" >> SIZE_INFO
          for file in cloudflared-linux-*; do
            if ./$file --version >/dev/null 2>&1; then
              echo "$file: OK" >> SIZE_INFO
            else
              echo "$file: FAILED" >> SIZE_INFO
              exit 1
            fi
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cloudflared
          name: cloudflared
          body: |
            Cloudflared Version: ${{ steps.get_version.outputs.latest_version }}
            
            Automated release of cloudflared binaries with different compression levels.
            
            ```
            $(cat SIZE_INFO)
            ```
            
            Compression levels:
            - 2x: Basic compression, faster decompression
            - 5x: Medium compression, balanced performance
            - 9x: Maximum compression, slower decompression
            
            All binaries have been verified to work correctly.
            SHA256 checksums are provided in SHA256SUMS file.
          files: |
            cloudflared-linux-amd64
            cloudflared-linux-arm64
            cloudflared-linux-amd64-2x
            cloudflared-linux-arm64-2x
            cloudflared-linux-amd64-5x
            cloudflared-linux-arm64-5x
            cloudflared-linux-amd64-9x
            cloudflared-linux-arm64-9x
            SHA256SUMS
            SIZE_INFO
          draft: false
          prerelease: false

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
